apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  containers:
    - name: node
      image: node:18.7-buster
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 1
          memory: 4Gi
